# Generated by Django 4.1.7 on 2023-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Prose', 'Проза'), ('Poetry', 'Поэзия')], max_length=6, null=True),
        ),
    ]
