# Generated by Django 4.1.7 on 2023-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_book_rating_alter_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='I', max_length=100)),
                ('last_name', models.CharField(default='Am', max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
