# Generated by Django 4.1.7 on 2023-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_character_book_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1),
        ),
    ]
