# Generated by Django 4.1.7 on 2023-04-17 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_relic_alter_character_character_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
