# Generated by Django 4.1.7 on 2023-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0014_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='', verbose_name='Файл')),
            ],
        ),
    ]
