# Generated by Django 4.1.7 on 2023-05-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_uploadfilesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFilesModel',
            new_name='UploadedFiles',
        ),
    ]
