# Generated by Django 4.1.7 on 2023-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_rename_uploadfilesmodel_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='uploaded_file',
            field=models.FileField(upload_to='uploaded_files', verbose_name='Файл'),
        ),
    ]
